CONDENSE = "Condense the following text to make it more concise:\n\n{}"
WORLD_BUILDING = {
    'MAIN_CHARACTER': "Create a main character based on the following seed data:\n{}\nThe character should have a name, date_of_birth, race, gender, and current_date_time. The current_date_time should be the datetime the character is currently living in. Please use standard date format. Please output to JSON format.",
    'MAIN_CHARACTER_SKILLS': "Generate a list of skills for this main character:\n{}\nBased on the following seed data:\n{}\nEach skill should have a name and description. Please output to JSON format.",
    'MAIN_CHARACTER_STATUSES': "Generate a list of statuses for this main character:\n{}\nBased on the following seed data:\n{}\nEach status should have a name, description, type, and duration (in seconds). Please include buffs and debuffs. Please output to JSON format.",
    'LOCATIONS': "Generate a list of locations that are all in close proximity based on the following seed data:\n{}\nEach location should include a name, description, longitude, latitude, type, climate, and terrain. Please output to JSON format.",
    'SUB_LOCATIONS': "Generate a list of areas or buildings that are all in close proximity inside this location:\n{}\nBased on the following seed data:\n{}\nEach location should include a name, description, longitude, latitude, type, climate, and terrain. Please output to JSON format.",
    'SURROUNDING_CHARACTERS': "Generate a list of characters that are all in close proximity inside this location:\n{}\nBased on the following seed data:\n{}\nEach character should have a name, date_of_birth, race, and gender. Please use standard date format. Please output to JSON format.",
    'CHARACTER_EVENT': "Create an event for this character:\n{}\nWho is currently in this location:\n{}\nBased on the following seed data:\n{}\nThe event should have a name, description, type, and role. The role should be the characters role in the event. Please output to JSON format."
} 